### ISSUE TITLE
Rex DSL functions generate 'no visible global' NOTEs when used in other packages.

### ISSUE THREAD

**Issue by jimhester** [kevinushey/rex#23]
If you use `rex` within another package and use any of the rex shortcuts or functions, e.g.

``` r
test <- function() rex(anything)
```

It generates the following NOTEs when you use R CMD check

```
* checking R code for possible problems ... NOTE
test: no visible binding for global variable ‘anything’
```

This seems to be because R CMD check does not understand the non-standard-evaluation rex uses.

I am not sure what we can do to fix this, @kevinushey any ideas?  Maybe we just go back to exporting everything?

**Comment by nr0cinu** [comment]
What would the best place to put this be?

[Looking](https://github.com/search?q=org%3Ar-lib%20rex%3A%3Aregister_shortcuts&type=code) at other `r-lib` packages, they either put it in `R/AAA.R`, `R/zzz.R` (in `.onLoad`), or somewhere else.
