### ISSUE TITLE
There seems to be no "r-cran-rex" package for Debian

### ISSUE THREAD

**Issue by krlmlr** [kevinushey/rex#43]
Trying: https://travis-ci.org/krlmlr/memoise/builds/80190423

CC @eddelbuettel.

If this package was on Debian, Travis runs could be much faster (e.g., if covr with all its dependencies is installed from Debian and not from source).

(Sorry: Travis runs on Ubuntu, it's not there, but it also doesn't seem to be on Debian.)

**Comment by eddelbuettel** [comment]
I suppose this can  be closed.  

There are > 7k CRAN packages; turning them into r-cran-* involved (at least some) manual labour.  I [blogged about how a PPA can help](http://dirk.eddelbuettel.com/blog/2015/07/26#evading_the_hadley_tax_faster_travis_tests) so Kirill could just open his own PPA and place a r-cran-rex there for his .travis.yml to use.

**Comment by krlmlr** [comment]
Thanks, Dirk. I missed that blog post.

I think we need custom images for CI, and rocker is a great step forward in this direction. Thanks for your effort (and for the effort of everybody else involved) in both the Debian packages and the rocker images.

One system that supports custom Docker images is wercker, but they are overly greedy with the GitHub permissions they require (wercker/support#20). Let's see how things evolve.

**Comment by eddelbuettel** [comment]
Doesn't Circle CI now also support Docker images? Been meaning to look at this.  

Greetings from (rainy, of course) London.

**Comment by krlmlr** [comment]
Yeah, and I guess Shippable too, and perhaps by now others. Circle was too expensive for me (and to recommend it for general use) last time I checked. I developed [my own wercker workflow](http://krlmlr.github.io/from-zero-to-tested-in-five-minutes/) a few months ago...

**Comment by jimhester** [comment]
Rex is an R only package with very limited required dependencies (https://github.com/kevinushey/rex/blob/525f92e7f9a8bdc9379a06633d871833c7c0dd78/DESCRIPTION#L16-L17), so having a debian build wouldn't change things very much IMHO.

On the topic of build systems @krlmlr you may not have seen but travis now supports docker containers as well (http://docs.travis-ci.com/user/docker/).

I have not had time to experiment with them yet to see if they will help remedy this problem, but you may want to explore it.

**Comment by krlmlr** [comment]
Thanks, Jim. `rex` is the only package that's missing in the rather sizable list of dependencies for `covr`.

Docker support in Travis... well, that might change matters indeed.

**Comment by eddelbuettel** [comment]
Right re R-only.  That should not bind.  And yes -- we need to get on with Docker/Rocker/Travis integration.
