### ISSUE TITLE
checking the correctness or regexes

### ISSUE THREAD

**Issue by piccolbo** [kevinushey/rex#44]
I started writing something very similar to rex before running  into it -- insufficient research on my part I suppose. The only big difference I see is that rex doesn't check for correctness of regexes before creating a regex object. When creating complex regexes from smaller parts, I find it very important to be able to rely on the small parts to be correct, and to have the failure message to be as informative as possible. For instance:

```
rex(regex("abc["), "def")
abc[def
```
succeeds, then at the first use

```
grep(rex(regex("abc["), "def"), "")
Error in grep(rex(regex("abc["), "def"), "") : 
  invalid regular expression 'abc[def', reason 'Missing ']''
```

Whereas the equivalent in my prototype is

```
rx(rxq("abc["), "def")
Error in grep(x, "") : 
  invalid regular expression 'abc[', reason 'Missing ']''
```

This is part of a three pronged approach to complex regex

1. readability
2. break down into named parts and compose
3. regex correctness at creation time, not use

It seems to me rex shares the first two, but not  the third. I was wondering if there would be an interest in accepting a patch to add the third prong to rex. There is a performance penalty to pay, a call to grep every time the regex class attribute is bestowed upon a string. Also, composition into a larger regex requires every operand to be cast to regex prior to pasting. Different approaches may exist, but I am not aware of them (in python, I would compile the regex), and I'd be happy to consider them. The only firm point of this proposal is the third prong. Thanks

**Comment by jimhester** [comment]
I would definitely be interested in a patch.

The main reason we don't currently check for correctness is I did not know of or have a good way to check for correctness.  I assume from your mention of `grep()` that you have a regex that validates regex syntax? Or just passing the regex to `grep()` with no value to see if it throws an error when it tries to compile the pattern (probably the better option)?

I don't think the performance issue would be a large problem, typically you are using the same regex on a large vector of values (with one call to `grep()` or the like), so even if there is an time increase in the initial regex construction the overall execution time is dominated by matching against the vector.

**Comment by piccolbo** [comment]
Thanks. 
The latter option as you guessed. Code from `regez`, with classnames changed

```
assert.valid.regex =
  function(x)
    is.regex(x) || is.integer(grep(x, ""))

is.regex = function(x) "regex" %in% class(x)
```

My estimate is that we need to check it in functions `regex`, `character_class`, `or` and `p` (on the  arguments). If you are aware of any other spots where characters are transformed into regexes or a paste or other operation that could destroy regex-correctness of arguments please let me know.

**Comment by piccolbo** [comment]
I guess I hit a roadblock. With the checks in, this test fails

```
rex(
    capture(name = "fruit", or("apple", "orange")),
    "=",
    capture_group("fruit")
    )
```

And it should, since the first arg is not a correct regex. It seem I had wrongly assumed that rex built correct regex from regexes and not from more general fragment. If that assumption is wrong, than this issue makes no sense. regez has not arrived to dealing with the capture issue,  so I am not sure how it would have dealt with this.

**Comment by jimhester** [comment]
Two things here,

1. You need to make sure to pass `perl = TRUE` to `grep()`, as named captures work only with PCRE.  The first arg is valid using PCRE 
```r
grep(rex:::capture(name = "fruit", rex:::or("apple", "orange")), "", perl = TRUE)
#> integer(0)
```
2. `capture_group()` is only going to work if a capture group was defined earlier in the expression, you could do this artificially for just the check if you wanted.
```r
grep(rex:::capture_group("fruit"), "", perl = TRUE)
#> Warning in grep(rex:::capture_group("fruit"), "", perl = TRUE) :
#>   PCRE pattern compilation error
#>         'reference to non-existent subpattern'
#>         at '}'
#> Error in grep(rex:::capture_group("fruit"), "", perl = TRUE) :
#>   invalid regular expression '\g{fruit}
```

**Comment by piccolbo** [comment]
As to 1 OK but it raises the question of generating other flavors of regex. My original use case was SQL queries, and I don't even know what flavor they take. As to two, I think it's a blow to my strategy. A capture group is not a correct regular expression of its own and it invalidates everything it's present in until the appropriately named `capture` is added to the expression. The idea to build valid expressions from valid expressions is not compatible with this.

**Comment by piccolbo** [comment]
Also, character_classes are  not correct regexes

```
grep(upper, "", perl = TRUE)
Error in grep(upper, "", perl = TRUE) : 
  invalid regular expression '[:upper:]'
In addition: Warning message:
In grep(upper, "", perl = TRUE) : PCRE pattern compilation error
	'POSIX named classes are supported only within a class'
	at '[:upper:]'
```

**Comment by piccolbo** [comment]
This is becoming a rewrite. Maybe bad idea.
