### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dpsanders** [kevinushey/rex#49]
What is the license for this package? The license file only contains a copyright statement, but has no open source license text. This means that strictly speaking it is illegal for anyone to use / modify it.

**Comment by jimhester** [comment]
It is [MIT](https://github.com/kevinushey/rex/blob/master/DESCRIPTION#L17), and follows the required CRAN guidelines for licensing https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing. In particular that LICENSE not include the full text if it is one of the standard licenses at https://www.R-project.org/Licenses/

**Comment by dpsanders** [comment]
Thanks. I don't know the CRAN conventions and I see that the information is pretty hidden inside a wall of text in the DESCRIPTION file. It seems odd that the LICENSE file doesn't even state which license is used.

**Comment by dpsanders** [comment]
The CRAN guidelines are certainly confusing, but there is a sentence "The optional file LICENSE/LICENCE contains a copy of the license of the package."

**Comment by kevinushey** [comment]
It's weird, but it's how CRAN mandates packages released under the MIT license are prepared.

It's more clear on the CRAN landing page: https://cran.r-project.org/package=rex

If this seems awkward, I suggest bringing it up with CRAN -- I don't think there's anything to change here.

**Comment by dpsanders** [comment]
Thanks.
