### ISSUE TITLE
Cannot avoid escaping of regular expression vectors

### ISSUE THREAD

**Issue by fangly** [kevinushey/rex#52]
Hi there,

I have some issues with vectors of regular expressions being escaped when I want them not to:
```
root<- c(
  unix = rex("/"),
  win  = rex(letter, ":")
)
regex <- rex(start, or(root), end)
print(re_matches(c("/", "C:"), regex)) 
# the result is: TRUE FALSE
# but should be: TRUE TRUE
```

I get the wrong result because `root` is of class `character` and `or()` escapes character vectors. No problem, I should be able to coerce this to class `regex` using `as.regex(root)`. No, this immediately escaped `root`.

I found two non-obvious/pretty workarounds:
1. do `class(root) <- "regex"`
2. use `list()` instead of `c()`

How I imagine things could work:
1. there could be a `c.regex()` method that would produce regular expression vectors (without escaping, similarly to `list()`)
2. `as.regex()` could have an option to avoid escaping when coercing character vectors or lists, e.g. `as.regex(root, escape=FALSE)`

Cheers,

Florent

**Comment by jimhester** [comment]
You just need to always use `list()`, the problem with `c.regex()` is `c()` always coerces to the lowest input, so if you try to mix regex objects with regular characters they are coerced to characters. I think it would be more confusing if `c()` works sometimes (when you have all regex objects) and not others.

The other thing you can do is explicitly wrap the part that is already a regex with `regex()`.

``` r
library(rex)
root<- c(
  unix = rex("/"),
  win  = rex(letter, ":")
)
regex<- rex(start, or(regex(root)), end)
re_matches(c("/", "C:"), regex)
#> [1] TRUE TRUE
```

**Comment by fangly** [comment]
Thanks for the reply, Jim!

I usually avoid using lists unless I have to, i.e. if the content is heterogeneous or nested. So, I think your `regex()` suggestion is a good fit for what I was trying to do (I did not realize that `regex()` is a base function).

### Suggestion
The `as.regex` documentation states "Simply escape the Object". I suggest adding there that one can avoid escaping already-quoted vectors by wrapping them in `regex()`.
