### ISSUE TITLE
Remove {lazyeval}

### ISSUE THREAD

**Issue by lorenzwalthert** [kevinushey/rex#75]
The {layzeval} package is considered retired according to its README and {rlang} is suggested as a replacement. {lazyeval} is [not often](https://github.com/kevinushey/rex/search?q=lazyeval) used in {rex} and it would cut down the dependency graph of [various packages](https://cran.r-project.org/web/packages/rex/index.html), most prominently {covr}, {lintr}. Would you consider removing it? I won't have time to contribute the removal.
cc: @MichaelChirico

**Comment by kevinushey** [comment]
That seems reasonable to me.
